baseURL = "https://soeren-helms.de/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Soeren Helms"

[blackfriday]
  extensions = ["hardLineBreak"]

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Soeren Helms"
  email = "me@soeren-helms.de"
  description = "Personal Info"
  bio = "Entrepreneur, Student, \nProgrammer, Human."
  avatar = "img/avatar.jpg"
  favicon = "img/favicon.ico"
  error404 = "There is no such page."

  [params.contact]
    linkedin = "https://www.linkedin.com/in/s%C3%B6ren-helms-774189121/"
    gitlab = "https://git.lumos.city/soerenhelms"
    instagram = "https://www.instagram.com/soerenh99"
    spotify = "https://open.spotify.com/user/soerenhelms"
    envelope = "mailto:me@soeren-helms.de"
    building = "https://repronik.it"
    