name: Publish

on:
  push:
    branches:
    - master
  schedule:
    - cron:  '30 6 * * 2'

jobs:
  Deploy:
    runs-on: ubuntu-18.04
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.74.2'
        extended: true

    - name: Build
      run: hugo --minify

    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        git-ftp-args: --insecure --all
        ftp-server:  soeren-helms.de
        ftp-username: ${{ secrets.FTP_USER }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./public/
